version: '3'

services:
  mapd-core:
    image: 'mapd/mapd-ce-cpu'
    ports:
      - 9090:9090
      - 9091:9091
      - 9092:9092
    volumes:
      - ./mapd-ml-storage:/mapd-storage
    ipc: host
  mapd-ml-cpu:
    image: 'mapd-ml-cpu'
    ports:
      - 8888:8888
    links:
      - mapd-core
    ipc: host
